image: Visual Studio 2017

clone_folder: c:\demolito

before_build:
  - set PATH=c:\msys64\usr\bin;c:\msys64;%PATH%
  - pacman -Syuu --noconfirm
  - pacman -Syuu --noconfirm
  - pacman -Syuu --noconfirm --needed mingw-w64-x86_64-gcc

build_script:
  - make no_popcnt CC=gcc
  - make popcnt CC=gcc
  - make pext CC=gcc
  - 7z a demolito_no_popcnt demolito_no_popcnt.exe c:\msys64\usr\bin\msys-2.0.dll src\ makefile license Readme.md
  - 7z a demolito_popcnt demolito_popcnt.exe c:\msys64\usr\bin\msys-2.0.dll src\ makefile license Readme.md
  - 7z a demolito_pext demolito_pext.exe c:\msys64\usr\bin\msys-2.0.dll src\ makefile license Readme.md

test: off
deploy: off

artifacts:
  - path: '*.7z'
